# Example configuration for testing different MP3D scenes
# Copy this file and modify for your specific needs

# @package _global_

defaults:
  - /habitat/simulator: sim_sensors
  - /habitat/task: nav
  - _self_

habitat:
  task:
    type: Nav-v0
    reward_measure: distance_to_goal
    success_measure: success
    success_distance: 0.2
    goal_sensor_uuid: pointgoal
    measurements:
      distance_to_goal:
        type: DistanceToGoal
        distance_to: POINT
      success:
        type: Success
        success_distance: 0.2
      spl:
        type: SPL
      soft_spl:
        type: SoftSPL
      top_down_map:
        type: TopDownMap
        max_episode_steps: 1000
        map_padding: 3
        map_resolution: 2048  # Higher resolution for better detail
        draw_source: true
        draw_border: true
        draw_shortest_path: false
        draw_view_points: true
        draw_goal_positions: false
        draw_goal_aabbs: false
        fog_of_war:
          draw: false
          visibility_dist: 5.0
          fov: 90
      collisions:
        type: Collisions
    goal_format: POLAR
    dimensionality: 2

  simulator:
    type: Sim-v0
    forward_step_size: 0.25
    turn_angle: 10
    action_space_config: v0
    agents:
      main_agent:
        height: 1.5
        radius: 0.1
        sim_sensors:
          rgb_sensor:
            type: HabitatSimRGBSensor
            height: 720  # Higher resolution
            width: 1280
            hfov: 90
            position: [0.0, 1.25, 0.0]
            orientation: [0.0, 0.0, 0.0]
          depth_sensor:
            type: HabitatSimDepthSensor
            height: 720
            width: 1280
            hfov: 90
            min_depth: 0.0
            max_depth: 10.0
            position: [0.0, 1.25, 0.0]
            orientation: [0.0, 0.0, 0.0]
    habitat_sim_v0:
      enable_physics: false
      allow_sliding: true
      gpu_device_id: 0
      gpu_gpu2gpu: false

  environment:
    max_episode_steps: 1000
    iterator_options:
      cycle: false
      shuffle: false
      group_by_scene: false
      num_episode_sample: -1
      max_scene_repeat_episodes: -1
      max_scene_repeat_steps: 50000
      step_repetition_range: 0.2

  dataset:
    type: PointNav-v1
    split: val
    scenes_dir: data/scene_datasets/
    data_path: data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz
    # Example scenes - uncomment one or add your own
    scenes: ["17DRP5sb8fy"]      # Default scene
    # scenes: ["2azQ1b91cZZ"]     # Living room scene
    # scenes: ["5LpN3gDmAk7"]     # House scene
    # scenes: ["1LXtFkjw3qL"]     # Multi-room scene
    # scenes: ["29hnd4uzFmX"]     # Large house
    # scenes: ["ac26ZMwG7aT"]     # Modern house
