"""Stable request contracts for the two-stage ObjectNav runtime.

Historical JSON shapes are recognized only so callers receive a precise
migration error. The canonical runner accepts the ``target_info`` request
format generated by :mod:`reason_navi.preprocessing`.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any, Dict, Mapping, Optional, Sequence, Tuple


class ContractError(ValueError):
    """Raised when a runtime JSON document violates the public contract."""


class RequestFormat(str, Enum):
    """Recognized canonical and historical request shapes."""

    LEGACY_ACTION = "action"
    TARGET_INFO = "target_info"
    LEGACY_SEQUENCE = "sequence"


def _finite_float(value: Any, field_name: str) -> float:
    if isinstance(value, bool):
        raise ContractError(f"{field_name} must be a finite number")
    try:
        result = float(value)
    except (TypeError, ValueError) as exc:
        raise ContractError(f"{field_name} must be a finite number") from exc
    if not math.isfinite(result):
        raise ContractError(f"{field_name} must be a finite number")
    return result


def _vector(
    value: Any, expected_length: int, field_name: str
) -> Tuple[float, ...]:
    if isinstance(value, (str, bytes)) or not isinstance(value, Sequence):
        raise ContractError(
            f"{field_name} must contain {expected_length} finite numbers"
        )
    if len(value) != expected_length:
        raise ContractError(
            f"{field_name} must contain {expected_length} finite numbers"
        )
    return tuple(
        _finite_float(item, f"{field_name}[{index}]")
        for index, item in enumerate(value)
    )


def _mapping(value: Any, field_name: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise ContractError(f"{field_name} must be an object")
    return value


@dataclass(frozen=True)
class AgentState3D:
    """Habitat world pose using an ``[x, y, z, w]`` quaternion."""

    position: Tuple[float, float, float]
    rotation: Tuple[float, float, float, float]

    @classmethod
    def from_mapping(cls, value: Any) -> "AgentState3D":
        data = _mapping(value, "agent_state")
        position = _vector(data.get("position"), 3, "agent_state.position")
        rotation = _vector(data.get("rotation"), 4, "agent_state.rotation")
        magnitude = math.sqrt(sum(component * component for component in rotation))
        if magnitude <= 1e-12:
            raise ContractError("agent_state.rotation must be a non-zero quaternion")
        normalized = tuple(component / magnitude for component in rotation)
        return cls(position=position, rotation=normalized)  # type: ignore[arg-type]

    def as_dict(self) -> Dict[str, Any]:
        return {
            "position": list(self.position),
            "rotation": list(self.rotation),
        }


@dataclass(frozen=True)
class InitialState2D:
    """Legacy single-floor pose represented by ``[x, z]`` and yaw degrees."""

    position: Tuple[float, float]
    rotation: float

    @classmethod
    def from_mapping(cls, value: Any) -> "InitialState2D":
        data = _mapping(value, "initial_state")
        return cls(
            position=_vector(data.get("position"), 2, "initial_state.position"),
            rotation=_finite_float(
                data.get("rotation"), "initial_state.rotation"
            ),
        )

    @classmethod
    def compatibility_default(cls) -> "InitialState2D":
        return cls(position=(0.0, 0.0), rotation=0.0)

    def as_dict(self) -> Dict[str, Any]:
        return {
            "position": list(self.position),
            "rotation": self.rotation,
        }


@dataclass(frozen=True)
class TargetInfo:
    """Semantic goal and its selected two-dimensional world coordinate."""

    coordinate: Tuple[float, float]
    name: str

    @classmethod
    def from_mapping(cls, value: Any) -> "TargetInfo":
        data = _mapping(value, "target_info")
        name = data.get("name")
        if not isinstance(name, str) or not name.strip():
            raise ContractError("target_info.name must be a non-empty string")
        return cls(
            coordinate=_vector(
                data.get("coordinate"), 2, "target_info.coordinate"
            ),
            name=name.strip(),
        )

    def as_dict(self) -> Dict[str, Any]:
        return {"coordinate": list(self.coordinate), "name": self.name}


@dataclass(frozen=True)
class NavigationRequest:
    """Validated runtime view of a navigation request JSON document."""

    input_format: RequestFormat
    raw: Mapping[str, Any]
    command_groups: Tuple[Mapping[str, Any], ...]
    agent_state: Optional[AgentState3D]
    initial_state: Optional[InitialState2D]
    wall_mask: Optional[Path]
    map_metadata: Optional[Path]

    @classmethod
    def from_mapping(
        cls,
        value: Any,
        *,
        wall_mask_override: Optional[str] = None,
        map_metadata_override: Optional[str] = None,
        base_dir: Optional[Path] = None,
    ) -> "NavigationRequest":
        data = _mapping(value, "navigation request")

        agent_state = (
            AgentState3D.from_mapping(data["agent_state"])
            if data.get("agent_state") is not None
            else None
        )
        initial_state = (
            InitialState2D.from_mapping(data["initial_state"])
            if data.get("initial_state") is not None
            else None
        )
        if agent_state is None and initial_state is None:
            raise ContractError(
                "navigation request must provide agent_state or initial_state"
            )

        wall_mask_value = (
            wall_mask_override
            if wall_mask_override is not None
            else data.get("wall_mask")
        )
        if wall_mask_value is not None and not isinstance(
            wall_mask_value, (str, Path)
        ):
            raise ContractError("wall_mask must be a filesystem path")
        wall_mask = Path(wall_mask_value).expanduser() if wall_mask_value else None
        if wall_mask is not None and not wall_mask.is_absolute() and base_dir:
            wall_mask = base_dir / wall_mask

        map_metadata_value = (
            map_metadata_override
            if map_metadata_override is not None
            else data.get("map_metadata")
        )
        if map_metadata_value is not None and not isinstance(
            map_metadata_value, (str, Path)
        ):
            raise ContractError("map_metadata must be a filesystem path")
        map_metadata = (
            Path(map_metadata_value).expanduser() if map_metadata_value else None
        )
        if (
            map_metadata is not None
            and not map_metadata.is_absolute()
            and base_dir
        ):
            map_metadata = base_dir / map_metadata

        # Preserve the legacy entrypoint's precedence when documents contain
        # more than one format: action -> target_info -> sequence.
        if "action" in data:
            actions = data["action"]
            if (
                isinstance(actions, (str, bytes))
                or not isinstance(actions, Sequence)
                or not actions
            ):
                raise ContractError("action must be a non-empty list")
            first_action = _mapping(actions[0], "action[0]")
            input_format = RequestFormat.LEGACY_ACTION
            groups = (dict(first_action),)
        elif "target_info" in data:
            target = TargetInfo.from_mapping(data["target_info"])
            group: Dict[str, Any] = {"target_info": target.as_dict()}
            if wall_mask is not None:
                group["wall_mask"] = str(wall_mask)
            input_format = RequestFormat.TARGET_INFO
            groups = (group,)
        elif "sequence" in data:
            sequence = data["sequence"]
            if isinstance(sequence, (str, bytes)) or not isinstance(
                sequence, Sequence
            ):
                raise ContractError("sequence must be a list")
            input_format = RequestFormat.LEGACY_SEQUENCE
            groups = ({"sequence": list(sequence)},)
        else:
            raise ContractError(
                "navigation request must provide target_info; historical "
                "action or sequence shapes are recognized for migration errors"
            )

        return cls(
            input_format=input_format,
            raw=dict(data),
            command_groups=groups,
            agent_state=agent_state,
            initial_state=initial_state,
            wall_mask=wall_mask,
            map_metadata=map_metadata,
        )

    def simulator_states(self) -> Tuple[Dict[str, Any], Optional[Dict[str, Any]]]:
        """Return the two arguments expected by ``setup_scene_and_agent``.

        A 3-D state has priority, while the legacy 2-D compatibility value is
        still supplied because the existing simulator signature requires it.
        """

        initial = self.initial_state or InitialState2D.compatibility_default()
        return (
            initial.as_dict(),
            self.agent_state.as_dict() if self.agent_state is not None else None,
        )
